### ISSUE TITLE
Bug in linked code elements

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/omd#156] opened 2016-07-25 12:11 UTC
The following is correctly generated:

    > printf '[`id`](link)' | omd 
    <p><a href='link'><code>id</code></a></p>

The following is not:

     > printf '[`id`][linkref]\n[linkref]: link' | omd 
     <p><a href='link'>`id`</a></p>

**Comment by pw374** [comment] 2016-09-19 19:34
duplicate of https://github.com/ocaml/omd/issues/151

**Closed by pw374** 2016-09-19 19:34 UTC
