### ISSUE TITLE
utf-8 support

### ISSUE THREAD

**Issue by pw374** [ocaml/omd#27] opened 2013-09-11 13:20 UTC
(following https://github.com/pw374/omd/issues/25)

At some point, the OMD library will only accept utf-8 (and subsets of it such as ascii, of course) as input and will output utf-8 only. This verification will be done at the lexer level, using @dbuenzli's libraries. (I think the way of doing that is that the input of the lexer will be unicode-normalised.)

Html entities will be converted to what they represent when they are in the text, meaning that `Foo&copy;Bar` will become `Foo©Bar` but `<div>&copy;</div>` will remain `<div>&copy;</div>`. This will allow people to write programs to, say, easily check that 2 lists items are actually the same, even if one is `Foo©Bar` and the other is `Foo&copy;Bar`. This will be done at the parser level.

As for non-valid html entities, such as `&foobar;`, I'm inclined to convert them to `&amp;foobar;` because that would be more in the spirit of Markdown, as far as I understand it.

Concerning the link references, the lowercase/uppercase issue will be resolved later for non-ascii characters, as the matching between lowercase and uppercase characters for unicode is not as trivial and @dbuenzli hasn't implemented a `to_lowercase`-ish function for unicode. (Note that currently, it uses String.lowercase which actually works on iso-8859-1, I might just get rid of that and use a custom function that works with ascii because it's trivial enough.)

So, all that would be for omd 1.0.

**Comment by nojb** [comment] 2020-06-20 14:24
Closing this as a kind of duplicate of #182.

Duplicate of #182

**Closed by nojb** 2020-06-20 14:24 UTC
Labels: feature
