### ISSUE TITLE
Support footnotes

### ISSUE THREAD

**Issue by Drup** [ocaml/omd#149] opened 2015-09-14 05:30 UTC
I don't really care which syntax you choose. I personally like this one:

```
Foo[^1] Bar

[^1]: A footnote.
```

(tbh, I didn't even knew it was non standard ...)

**Comment by XVilka** [comment] 2019-09-29 11:10
Indeed, would be really nice to have.

**Comment by nojb** [comment] 2020-06-20 13:57
Makes sense, putting this one as a duplicate of #188

**Closed** 2020-06-20 13:58 UTC
